// Generated by Wrangler by running `wrangler types`

//  interface Env {
// 	"0": {};
// 	DB: D1Database;
// 	AI: Ai;
// }

interface CloudflareBindings {
	"0": {};
	MY_KV: KVNamespace;
	DB: D1Database;
	AI: Ai;
	STRIPE_SECRET_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	OPEN_AI_KEY: string;
}
